export * from './actionTest';


export const CONSTANTS = {
    ADD_BOARD : "ADD_BOARD",
    ADD_LIST : "ADD_LIST",
    ADD_CARD : "ADD_CARD",
    DELETE_BOARD : "DELETE_BOARD",
    DELETE_CARD : "DELETE_CARD",
    DELETE_LIST : "DELETE_LIST",
    EDIT_BOARD: "EDIT_BOARD",
    EDIT_LIST: "EDIT_LIST",
    EDIT_CARD: "EDIT_CARD",
    GET_USERS: "GET_USERS",
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_LISTS: "GET_LISTS",
    GET_CARDS: "GET_CARDS",
    CREATE_BOARD: "CREATE_BOARD",
    EDIT_NAME: "EDIT_NAME",
    EDIT_PASSWORD: "EDIT_PASSWORD",
    DELETE_USER: "DELETE_USER"
}